export const BRAND_NAME = 'Magic Studio'
export const BRAND_SHORT_NAME = 'Magic'
export const BRAND_OWNER = 'Krish Tyagi'
export const BRAND_REPO_URL = 'https://github.com/krishtyagi260605-gif/magic-studio-demo-model-magic-studio'
export const BRAND_LICENSE_URL = `${BRAND_REPO_URL}/blob/main/LICENSE`
export const BRAND_TERMS_URL = BRAND_REPO_URL
export const BRAND_PRIVACY_URL = BRAND_REPO_URL
export const BRAND_HELP_URL = BRAND_REPO_URL
export const BRAND_UPDATES_URL = BRAND_REPO_URL
export const BRAND_CONTACT_EMAIL = 'hello@magicstudio.dev'
export const BRAND_CONTACT_MAILTO = `mailto:${BRAND_CONTACT_EMAIL}`
